### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by vercotux** [yii2mod/yii2-enum#1]
This extension is the best out there, but how can I use it with internationalization?

It is impossible in PHP to declare the static $list array in the following way:

```
public static $list = [
    self::NO    => \Yii::t('yesNo','No'),
    self::YES   => \Yii::t('yesNo','Yes'),
];
```

Any ideas?

**Comment by vercotux** [comment]
One solution is to declare the $list from outside right after the class declaration like this:

```
YesNo::$list = [
    YesNo::NO    => \Yii::t('yesNo','No'),
    YesNo::YES   => \Yii::t('yesNo','Yes'),
];
```

But this is also **not** possible because $list is _private_.

**Comment by vercotux** [comment]
Tested. Making $list _public_ solves the problem. Can we make it _public_?

**Comment by disem** [comment]
How about `getLabel` method? Take a look https://github.com/yii2mod/yii2-enum/blob/master/helpers/BaseEnum.php#L143

**Comment by vercotux** [comment]
It works for a single item, but that is not very useful because I mainly need _listData_ which returns untranslated values. Also I need to use message categories other than 'enum'.

**Comment by disem** [comment]
resolved via https://github.com/yii2mod/yii2-enum/commit/5786e5178e32593f716703b5bb01fb686837af30
