### ISSUE TITLE
Enum Migrations

### ISSUE THREAD

**Issue by vercotux** [yii2mod/yii2-enum#2]
An incredibly useful feature would be the ability to migrate/synchronize enums into the database. This is just a proposal. I will probably end up implementing it myself, but I wanted to share the idea.

Having a class like _EnumMigration_ which extends from _Migration_ that:
- Requires one single parameter: the enum class
- Creates the enum table in the database if it does not yet exist
- Inserts all missing enum KV pairs
- Removes all nonexisting enum KV pairs

**Comment by disem** [comment]
Can you provide use case for this feature? Not sure I understand it's purpose..
