### ISSUE TITLE
PHPdoc credit points to wrong github URL

### ISSUE THREAD

**Issue by vercotux** [yii2mod/yii2-enum#3]
Just wanted to point out [the URL in BaseEnum.php](https://github.com/yii2mod/yii2-enum/blob/68a15fdba1dd8fe52cd88d7db41912f33403a1ba/helpers/BaseEnum.php#L13) should probably point to this repository ;)

Loving this extension btw. Really good stuff.

**Comment by disem** [comment]
This url was leading to the source of the reflection related methods I've used.
Since it was deleted by author i removed this mention, but respect to the author anyway :)
